

export interface PromptTemplate {
    id: string;
    category: string;
    title: string;
    description: string;
    prompt: string;
    beforeImage: string;
    afterImage: string;
}

export const vxplTemplates: PromptTemplate[] = [
    {
        id: 'pro_headshot_1',
        category: 'Professional',
        title: 'template_pro_headshot_1_title',
        description: 'template_pro_headshot_1_description',
        prompt: `Analyze the person in the provided photo. Do not change their face or likeness. Recreate the image by placing the person in a dark gray professional business suit. The background should be a subtle, out-of-focus modern office environment. The lighting should be soft and flattering, characteristic of a professional headshot. Ensure the final image is a photorealistic, high-quality corporate headshot.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-after.webp',
    },
    {
        id: 'product_mockup_1',
        category: 'Professional',
        title: 'template_product_mockup_1_title',
        description: 'template_product_mockup_1_description',
        prompt: `Identify the main product in the user's image. Flawlessly remove its original background. Place the isolated product on a clean, minimalist light gray studio background. Add a soft, realistic shadow beneath the product to ground it in the scene. The final image should be a high-resolution, professional product shot.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-product-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-product-after.webp',
    },
    {
        id: 'arch_viz_1',
        category: 'Professional',
        title: 'template_arch_viz_1_title',
        description: 'template_arch_viz_1_description',
        prompt: `Take the building from the user's image and render it as a photorealistic architectural visualization. The materials should be modern: concrete, glass, and dark wood. The time of day should be late afternoon, with the sun casting long, soft shadows. The building should be surrounded by lush, green landscaping and a few modern outdoor furniture pieces. The final image must be indistinguishable from a high-end architectural render.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-archviz-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-archviz-after.webp',
    },
    {
        id: 'professional_blueprint_1',
        category: 'Professional',
        title: 'template_professional_blueprint_1_title',
        description: 'template_professional_blueprint_1_description',
        prompt: `Analyze the building in the provided photograph. Your task is to convert it into a clean, detailed architectural blueprint drawing. The final image should consist of white lines on a classic blueprint-blue background. Include schematic details like dimensions and annotations where appropriate for an authentic look. Do not show the original photo, only the blueprint rendering.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-archviz-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-blueprint-after.webp',
    },
    {
        id: 'food_photography_1',
        category: 'Professional',
        title: 'template_food_photography_1_title',
        description: 'template_food_photography_1_description',
        prompt: `Analyze the food dish in the photo. Recreate the image as a professional gourmet food photograph. The lighting should be dramatic and appetizing, with soft shadows. The background should be a dark, rustic wooden table. Add subtle, out-of-focus elements like a wine glass or fresh herbs to style the scene. The final image must look like a shot from a high-end cooking magazine.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-food-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-food-after.webp',
    },
    {
        id: 'photo_restoration_1',
        category: 'Utility',
        title: 'template_photo_restoration_1_title',
        description: 'template_photo_restoration_1_description',
        prompt: `Act as a professional photo restoration expert. Analyze the provided vintage photograph for damage such as scratches, tears, stains, and discoloration. Your task is to meticulously repair these imperfections, restore faded colors to their natural state, and enhance the overall sharpness and clarity of the image. It is critical to preserve the original character, subjects, and authenticity of the photograph. Do not add or remove elements; only restore and enhance.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-restore-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-restore-after.webp',
    },
    {
        id: 'image_upscale_1',
        category: 'Utility',
        title: 'template_image_upscale_1_title',
        description: 'template_image_upscale_1_description',
        prompt: `CRITICAL INSTRUCTION: Execute a high-fidelity upscale to [Specify 2K or 4K] resolution on the provided image. The output MUST exhibit a significant increase in detail, clarity, and texture resolution. This is a non-negotiable directive to perform a genuine upscale, not a simple resize. Preserve original content and composition. Example for 4K: "Execute a high-fidelity upscale to 4K resolution on the provided image..."`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-upscale-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-upscale-after.webp',
    },
    {
        id: 'season_change_1',
        category: 'Utility',
        title: 'template_season_change_1_title',
        description: 'template_season_change_1_description',
        prompt: `Analyze the provided outdoor photo. Your task is to realistically transform the scene into a winter landscape. Cover the ground, trees, and other surfaces with a layer of fresh, white snow. The sky should be a clear, crisp winter blue, and the lighting should be bright but soft, as if from a low winter sun. Ensure the snow looks natural and interacts believably with the objects in the scene.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-winter-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-winter-after.webp',
    },
    {
        id: 'utility_change_bg_1',
        category: 'Utility',
        title: 'template_utility_change_bg_1_title',
        description: 'template_utility_change_bg_1_description',
        prompt: `Analyze the primary subject in the user's provided image. Your task is to flawlessly isolate this subject and remove the original background. Then, place the subject onto a new background: a photorealistic, sunny tropical beach with turquoise water and white sand. Ensure the lighting on the subject is adjusted to naturally match the bright, sunny lighting of the new beach environment. The final composition should be seamless and believable.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-change-bg-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-change-bg-after.webp',
    },
    {
        id: 'golden_hour_1',
        category: 'Photography',
        title: 'template_golden_hour_1_title',
        description: 'template_golden_hour_1_description',
        prompt: `Analyze the person in the portrait. Your task is to realistically relight the entire scene to match the "golden hour" (just before sunset). The light should be warm, golden, and coming from a low angle, creating long, soft shadows. Add a subtle lens flare effect. The background should be slightly blurred (bokeh) to keep the focus on the subject. Do not change the person's identity.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-golden-hour-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-golden-hour-after.webp',
    },
    {
        id: 'style_transfer_1',
        category: 'Artistic',
        title: 'template_style_transfer_1_title',
        description: 'template_style_transfer_1_description',
        prompt: `Analyze the user's provided image to understand its core subject and composition. Your task is to completely repaint the user's image, faithfully recreating it in the distinct and iconic style of Vincent van Gogh's painting "The Starry Night," paying close attention to the swirling brushstrokes, dramatic color palette, and emotional texture. The original subject of the user's photo must remain clearly recognizable.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-after.webp',
    },
    {
        id: 'comic_style_1',
        category: 'Artistic',
        title: 'template_comic_style_1_title',
        description: 'template_comic_style_1_description',
        prompt: `Transform the provided photograph into a classic American comic book panel from the 1980s. Redraw the subjects with bold, black ink outlines. Apply a color palette of vibrant, saturated primary colors. Add a halftone dot pattern (Ben-Day dots) for shading and texture. The overall composition should be dynamic. Preserve the likeness of the subjects in the photo.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-comic-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-comic-after.webp',
    },
    {
        id: 'hologram_1',
        category: 'Abstract & Sci-Fi',
        title: 'template_hologram_1_title',
        description: 'template_hologram_1_description',
        prompt: `Isolate the main subject from the provided image. Recreate the subject as a glowing, semi-transparent blue hologram. The hologram should have visible scan lines and a subtle digital flicker effect. Place the hologram in a dark, futuristic laboratory setting. Ensure the hologram emits its own light, casting a blue glow on the surrounding environment.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-hologram-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-hologram-after.webp',
    },
    {
        id: 'artistic_color_splash_1',
        category: 'Artistic',
        title: 'template_artistic_color_splash_1_title',
        description: 'template_artistic_color_splash_1_description',
        prompt: `Transform the provided image into a black and white photograph. However, identify the [SPECIFY OBJECT OR COLOR TO KEEP, e.g., 'red dress'] and keep only that specific element in its original, vibrant color. All other parts of the image must be monochrome. The final image should have a high-contrast, artistic look.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-color-splash-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-color-splash-after.webp',
    },
    {
        id: 'rpg_character_1',
        category: 'Character Design',
        title: 'template_rpg_character_1_title',
        description: 'template_rpg_character_1_description',
        prompt: `Using the person in the photo as a reference for the face and likeness, recreate them as a fantasy RPG character. The style should be a detailed, realistic digital painting. The character is a wise elf mage. They should have pointed ears, long silver hair, and be wearing ornate, magical robes. The background should be an ancient, mystical library with glowing runes. The lighting should be magical and ethereal.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-rpg-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-rpg-after.webp',
    },
    {
        id: 'vector_logo_1',
        category: 'UI & Icons',
        title: 'template_vector_logo_1_title',
        description: 'template_vector_logo_1_description',
        prompt: `Analyze the provided simple sketch or object. Your task is to transform it into a clean, modern, minimalist vector logo. Use a simple color palette of dark blue and white. The final output should be a single, centered logo on a plain white background, with no trace of the original input image.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-after.webp',
    },
    {
        id: 'pixel_art_1',
        category: 'Artistic',
        title: 'template_pixel_art_1_title',
        description: 'template_pixel_art_1_description',
        prompt: `Analyze the person in the provided photo. Recreate them as a 3D voxel art character in the style of modern pixel art video games. The character should be blocky but recognizable. The lighting should be bright and colorful, casting sharp pixelated shadows. The background should be a simple, flat color gradient.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-pixel-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-pixel-after.webp',
    },
    {
        id: 'tilt_shift_1',
        category: 'Photography',
        title: 'template_tilt_shift_1_title',
        description: 'template_tilt_shift_1_description',
        prompt: `Transform the provided photograph into a convincing tilt-shift miniature scene. Apply a shallow depth of field, keeping a narrow band of the image in sharp focus while progressively blurring the foreground and background. Increase the color saturation and contrast slightly to enhance the "model" effect. The final image should look like a photograph of a detailed diorama.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-tilt-shift-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-tilt-shift-after.webp',
    },
    {
        id: 'creative_tattoo_design_1',
        category: 'Creative & Fun',
        title: 'template_creative_tattoo_design_1_title',
        description: 'template_creative_tattoo_design_1_description',
        prompt: `Take the core subject from the provided image and redraw it as a neo-traditional tattoo design. The design must feature bold, black outlines, a rich color palette, and intricate details. The final output should be a single, centered tattoo design on a plain white background, ready for a flash sheet.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-tattoo-after.webp'
    },
    {
        id: 'photo_film_noir_1',
        category: 'Photography',
        title: 'template_photo_film_noir_1_title',
        description: 'template_photo_film_noir_1_description',
        prompt: `Convert the provided image to a high-contrast black and white film noir style. The lighting should be dramatic and low-key, creating long, hard shadows (chiaroscuro). The atmosphere should be mysterious and moody. Keep the subject recognizable but immerse them in this classic cinematic aesthetic.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-comic-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-restore-after.webp',
    },
    {
        id: 'photo_wildlife_1',
        category: 'Photography',
        title: 'template_photo_wildlife_1_title',
        description: 'template_photo_wildlife_1_description',
        prompt: `Analyze the animal in the photo. Enhance the image to look like a professional wildlife photograph. Use a telephoto lens effect to create a shallow depth of field, making the background beautifully blurred. Adjust the lighting to be soft and natural, characteristic of early morning. Sharpen the focus on the animal's eyes. The final image should be hyper-detailed and look like an award-winning shot.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-winter-after.webp',
    },
    {
        id: 'photo_macro_1',
        category: 'Photography',
        title: 'template_photo_macro_1_title',
        description: 'template_photo_macro_1_description',
        prompt: `Take the provided image of an insect or flower and transform it into an ultra-macro photograph. Magnify the subject to reveal intricate details not visible to the naked eye. The lighting should be soft and diffused to highlight textures. The background should be a creamy, out-of-focus blur. The final image must be extremely sharp and detailed.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-product-after.webp',
    },
    {
        id: 'photo_long_exposure_1',
        category: 'Photography',
        title: 'template_photo_long_exposure_1_title',
        description: 'template_photo_long_exposure_1_description',
        prompt: `Transform the provided cityscape photo into a long exposure shot at night. If there are cars, turn their headlights and taillights into vibrant red and white trails of light. The surrounding buildings should remain sharp and detailed. Enhance the reflections on any wet pavement. The final image should be cinematic and moody.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-color-splash-after.webp',
    },
    {
        id: 'photo_drone_1',
        category: 'Photography',
        title: 'template_photo_drone_1_title',
        description: 'template_photo_drone_1_description',
        prompt: `Re-render the provided landscape photo as if it were taken from an aerial top-down drone perspective. The final image should showcase the abstract patterns and textures of the landscape from directly above. Enhance the colors and contrast to make the scene striking and photorealistic.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-winter-before.webp',
    },
    {
        id: 'utility_color_palette_1',
        category: 'Utility',
        title: 'template_utility_color_palette_1_title',
        description: 'template_utility_color_palette_1_description',
        prompt: `Analyze the provided image. Extract the 5 most dominant and harmonious colors. Your task is to generate a new image displaying this color palette. The output should show 5 clean, flat squares of color arranged horizontally on a white background. Below each square, include the corresponding hex code.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-after.webp',
    },
    {
        id: 'utility_texture_1',
        category: 'Utility',
        title: 'template_utility_texture_1_title',
        description: 'template_utility_texture_1_description',
        prompt: `Analyze the texture in the provided image (e.g., wood, stone, fabric). Your task is to regenerate it as a high-resolution, seamless, tileable texture. The final image must be able to be tiled perfectly without any visible seams. The lighting should be neutral and flat to ensure it can be used in any 3D environment.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-restore-after.webp',
    },
    {
        id: 'char_cyborg_1',
        category: 'Character Design',
        title: 'template_char_cyborg_1_title',
        description: 'template_char_cyborg_1_description',
        prompt: `Take the person from the provided photo and transform them into a cyberpunk cyborg. Do not change their face, but augment their body with sleek, black carbon fiber limbs and glowing neon blue circuitry. One eye should become a glowing optical sensor. Place them in a rain-slicked alley in a futuristic city with moody, cinematic lighting.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-rpg-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-hologram-after.webp',
    },
    {
        id: 'char_steampunk_1',
        category: 'Character Design',
        title: 'template_char_steampunk_1_title',
        description: 'template_char_steampunk_1_description',
        prompt: `Transform the person in the photo into a steampunk inventor. Keep their facial features, but give them brass goggles on their forehead and a clockwork mechanical arm. Dress them in a leather vest over a white shirt. The background should be transformed into a workshop filled with gears, blueprints, and strange contraptions. The style should be a detailed oil painting with warm lighting.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-rpg-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-rpg-after.webp',
    },
    {
        id: 'char_creature_1',
        category: 'Character Design',
        title: 'template_char_creature_1_title',
        description: 'template_char_creature_1_description',
        prompt: `Transform the animal in the provided photo into an ethereal forest spirit. Its body should be remade from translucent, glowing blue energy and shimmering leaves. Its horns or antlers should become gnarled branches with blooming flowers. Place it in an ancient, mossy forest at night, with magical moonlight filtering through the canopy.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-after.webp',
    },
    {
        id: 'env_solarpunk_1',
        category: 'Environment & Worlds',
        title: 'template_env_solarpunk_1_title',
        description: 'template_env_solarpunk_1_description',
        prompt: `Transform the provided city or landscape photo into a solarpunk utopia. The architecture should be a harmonious blend of futuristic white buildings and lush vertical gardens. Integrate gleaming solar panels and wind turbines into the design. The atmosphere must be bright, clean, and optimistic. The final image should be a photorealistic, 8k wide-angle shot.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-archviz-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-archviz-after.webp',
    },
    {
        id: 'env_floating_islands_1',
        category: 'Environment & Worlds',
        title: 'template_env_floating_islands_1_title',
        description: 'template_env_floating_islands_1_description',
        prompt: `Take the provided landscape and transform it into a breathtaking fantasy scene of floating islands at sunrise. Each island should have ancient ruins and giant, glowing trees. Add waterfalls that cascade from the edges of the islands into the clouds below. The style should be an epic digital painting with magical lighting.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-winter-before.webp',
    },
    {
        id: 'env_interior_1',
        category: 'Environment & Worlds',
        title: 'template_env_interior_1_title',
        description: 'template_env_interior_1_description',
        prompt: `Re-render the provided photo of a room into a luxurious Art Deco interior. The room should feature a geometric patterned rug, a plush velvet sofa, gold and brass accents, and a grand, sunburst-shaped mirror. The lighting must be elegant and warm. The final output should be a photorealistic, 4k architectural visualization.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-golden-hour-after.webp',
    },
    {
        id: 'art_surreal_1',
        category: 'Artistic',
        title: 'template_art_surreal_1_title',
        description: 'template_art_surreal_1_description',
        prompt: `Transform the provided image into a surrealist oil painting in the style of Salvador Dalí. Introduce surreal elements like melting objects, strange creatures, or illogical juxtapositions, while using the original image as a base for the composition. The final image should be highly detailed, symbolic, and dreamlike.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-tilt-shift-after.webp',
    },
    {
        id: 'art_ukiyo_e_1',
        category: 'Artistic',
        title: 'template_art_ukiyo_e_1_title',
        description: 'template_art_ukiyo_e_1_description',
        prompt: `Redraw the provided image in the style of a traditional Japanese Ukiyo-e woodblock print. Use flat, bold colors and strong black outlines. The composition should be stylized and elegant, capturing the essence of the original subject in this classic art form.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-winter-after.webp',
    },
    {
        id: 'ui_app_icon_1',
        category: 'UI & Icons',
        title: 'template_ui_app_icon_1_title',
        description: 'template_ui_app_icon_1_description',
        prompt: `Transform the subject of the provided image into a modern, minimalist app icon. The icon should be a stylized, friendly-looking representation of the subject. Use a bright color gradient. The icon must be a squircle shape, ready for iOS, and rendered as clean vector art, centered on a white background.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-after.webp',
    },
    {
        id: 'ui_game_icon_1',
        category: 'UI & Icons',
        title: 'template_ui_game_icon_1_title',
        description: 'template_ui_game_icon_1_description',
        prompt: `Based on the provided image, create a fantasy RPG skill icon for a game UI. The icon should have a unified, painterly style and be set within a circular stone border. The final icon should be a clear, distinct, and visually appealing representation of the original subject.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-pixel-after.webp',
    },
    {
        id: 'scifi_cosmic_1',
        category: 'Abstract & Sci-Fi',
        title: 'template_scifi_cosmic_1_title',
        description: 'template_scifi_cosmic_1_description',
        prompt: `Analyze the provided image of space. Transform it into a breathtaking photograph of a cosmic nebula, in the style of a Hubble Space Telescope image. Enhance the colors to be vibrant shades of pink, purple, and blue. Add sparkling new stars within the clouds of gas and dust to give the impression of a stellar nursery. The final image should be vast, awe-inspiring, and hyper-detailed.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-after.webp',
    },
    {
        id: 'scifi_alien_world_1',
        category: 'Environment & Worlds',
        title: 'template_scifi_alien_world_1_title',
        description: 'template_scifi_alien_world_1_description',
        prompt: `Transform the provided landscape into a panoramic view of an alien planet. The flora should be made bioluminescent, glowing with soft blue and purple light. Add two moons to the sky and change the sky to a purple hue. Add strange, crystalline rock formations throughout the landscape. The final image should be serene, magical, and mysterious.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-winter-before.webp',
    },
    {
        id: 'fun_food_monster_1',
        category: 'Creative & Fun',
        title: 'template_fun_food_monster_1_title',
        description: 'template_fun_food_monster_1_description',
        prompt: `Transform the food item in the provided image into a cute, friendly monster character. Give it cartoon eyes and a wide smile. The character should be waving. Render it in a 3D style with studio lighting and a shallow depth of field.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-food-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-food-after.webp',
    },
    {
        id: 'fun_animal_job_1',
        category: 'Creative & Fun',
        title: 'template_fun_animal_job_1_title',
        description: 'template_fun_animal_job_1_description',
        prompt: `Take the animal from the provided photo and place it in a human job setting. Add appropriate clothing and props. For example, if it's a cat, dress it as a librarian with tiny glasses. The final image should be highly detailed and photorealistic, but the mood should be charming and whimsical.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-rpg-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-golden-hour-after.webp',
    },
    {
        id: 'pro_infographic_1',
        category: 'Professional',
        title: 'template_pro_infographic_1_title',
        description: 'template_pro_infographic_1_description',
        prompt: 'Transform the provided chart or data visualization into a clean, modern vector infographic element. It should feature stylized shapes and an upward-trending arrow integrated into the design. Use a professional color palette of blue, green, and gray. The style should be flat design with subtle shadows. Isolate the final result on a white background.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-after.webp',
    },
    {
        id: 'photo_double_exposure_1',
        category: 'Photography',
        title: 'template_photo_double_exposure_1_title',
        description: 'template_photo_double_exposure_1_description',
        prompt: `Create a double exposure image. Use the person in the first provided image to create a silhouette. Fill this silhouette with the landscape from the second provided image. The two images should be blended seamlessly for an artistic and thoughtful effect. The final image should be monochrome with a slight blue tint.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-winter-after.webp',
    },
    {
        id: 'utility_qr_code_1',
        category: 'Utility',
        title: 'template_utility_qr_code_1_title',
        description: 'template_utility_qr_code_1_description',
        prompt: 'Artistically integrate a functional QR code that links to "https://google.com" into the provided image. The QR code\'s pattern should be creatively blended into the scene. For example, it could form the windows of a skyscraper in a city photo. The design must be creative while ensuring the QR code remains scannable.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-comic-after.webp',
    },
    {
        id: 'char_low_poly_1',
        category: 'Character Design',
        title: 'template_char_low_poly_1_title',
        description: 'template_char_low_poly_1_description',
        prompt: 'Transform the subject of the provided photo into a low poly art style character. The character should be composed of visible, flat-shaded polygons. The colors should be simple and vibrant. Place the character on a simple, flat ground plane against a clean background.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-pixel-after.webp',
    },
    {
        id: 'env_isometric_1',
        category: 'Environment & Worlds',
        title: 'template_env_isometric_1_title',
        description: 'template_env_isometric_1_description',
        prompt: 'Transform the provided photo of a room into a detailed isometric 3D render. The room should be recreated in a cute and slightly stylized voxel art style. The lighting should be warm. The final image should look like a miniature diorama.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-pixel-after.webp',
    },
    {
        id: 'art_line_art_1',
        category: 'Artistic',
        title: 'template_art_line_art_1_title',
        description: 'template_art_line_art_1_description',
        prompt: 'Trace the main subject of the provided photo to create a minimalist continuous single line drawing. The line should be clean, black, and flow smoothly to create the form. The style is elegant and simple. Isolate the final drawing on a plain white background.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-after.webp',
    },
    {
        id: 'scifi_fractal_1',
        category: 'Abstract & Sci-Fi',
        title: 'template_scifi_fractal_1_title',
        description: 'template_scifi_fractal_1_description',
        prompt: 'Transform the provided image into a highly detailed, mesmerizing 3D fractal art piece. The structure should have intricate, repeating patterns. The colors should be a vibrant, iridescent palette of blues, purples, and golds. The image should look like a journey into an infinitely complex mathematical world. 8k resolution with ray tracing.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-hologram-after.webp',
    },
    {
        id: 'fun_sticker_1',
        category: 'Creative & Fun',
        title: 'template_fun_sticker_1_title',
        description: 'template_fun_sticker_1_description',
        prompt: 'Turn the subject of the photo into a cute vinyl sticker design. Redraw it in a cute cartoon (kawaii) style. The character must have a thick white border for die-cutting. The colors should be bright and cheerful. Isolate the final design on a plain background.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-food-after.webp',
    },
     {
        id: 'pro_presentation_slide_1',
        category: 'Professional',
        title: 'template_pro_presentation_slide_1_title',
        description: 'template_pro_presentation_slide_1_description',
        prompt: 'Use the provided image as inspiration to create a background image for a business presentation title slide. The design should be abstract, modern, clean, and professional, featuring geometric shapes in a corporate blue and gray color scheme. There should be ample negative space on the right side to overlay text. Subtle, soft lighting. 4k resolution.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-after.webp',
    },
    {
        id: 'photo_anamorphic_1',
        category: 'Photography',
        title: 'template_photo_anamorphic_1_title',
        description: 'template_photo_anamorphic_1_description',
        prompt: 'Re-render the provided photo of a person on a city street at night as a cinematic shot captured with an anamorphic lens. The image should have a wide aspect ratio (2.39:1). Add characteristic horizontal blue lens flares from streetlights. The out-of-focus background lights (bokeh) should be rendered as oval-shaped. Add film grain and a moody color grade.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-golden-hour-after.webp',
    },
    {
        id: 'utility_storyboard_1',
        category: 'Utility',
        title: 'template_utility_storyboard_1_title',
        description: 'template_utility_storyboard_1_description',
        prompt: 'Convert the provided image into a single storyboard panel for a film. The style should be a clean, black and white pencil sketch. The composition should be clear and convey the emotion of the original scene. Add arrows to indicate camera movement (e.g., a slow zoom-in).',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-restore-after.webp',
    },
    {
        id: 'char_undead_1',
        category: 'Character Design',
        title: 'template_char_undead_1_title',
        description: 'template_char_undead_1_description',
        prompt: 'Transform the character in the photo into a terrifying undead knight. Keep their basic form but dress them in rusted, gothic plate armor. Make their eyes empty sockets that burn with an eerie green light. The background should become a desolate, misty graveyard. The final style should be dark fantasy digital painting.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-rpg-after.webp',
    },
    {
        id: 'env_post_apocalyptic_1',
        category: 'Environment & Worlds',
        title: 'template_env_post_apocalyptic_1_title',
        description: 'template_env_post_apocalyptic_1_description',
        prompt: 'Transform the provided city photo into a beautiful but desolate post-apocalyptic landscape. The ruins of the city should be overgrown with vines and trees. The atmosphere should be quiet, melancholic, and strangely peaceful, with sunset lighting. The final style should be a realistic matte painting.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-archviz-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-winter-before.webp',
    },
    {
        id: 'art_watercolor_1',
        category: 'Artistic',
        title: 'template_art_watercolor_1_title',
        description: 'template_art_watercolor_1_description',
        prompt: 'Repaint the provided image as a beautiful watercolor painting. The colors should be soft and translucent, with visible brush strokes and paper texture. The paint should bleed slightly at the edges, characteristic of the watercolor medium. The scene should be bright and cheerful.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-after.webp',
    },
    {
        id: 'ui_website_hero_1',
        category: 'UI & Icons',
        title: 'template_ui_website_hero_1_title',
        description: 'template_ui_website_hero_1_description',
        prompt: `Use the provided image as a style reference to create a high-resolution abstract background image for a tech company's website hero section. The design should feature flowing, organic shapes and lines in shades of blue and purple, with a subtle digital grid pattern overlaid. It should feel modern, dynamic, and professional. The composition should have negative space for text.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-hologram-after.webp',
    },
    {
        id: 'scifi_mecha_1',
        category: 'Abstract & Sci-Fi',
        title: 'template_scifi_mecha_1_title',
        description: 'template_scifi_mecha_1_description',
        prompt: 'Transform the vehicle or character in the provided image into a giant, heavily-armored mecha robot. The design should be industrial and practical, with visible hydraulics, wiring, and weapon systems. Place it in a hangar bay for servicing, with dramatic lighting to highlight its immense scale.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-comic-after.webp',
    },
    {
        id: 'fun_storybook_1',
        category: 'Creative & Fun',
        title: 'template_fun_storybook_1_title',
        description: 'template_fun_storybook_1_description',
        prompt: `Redraw the provided photo as an illustration for a children's storybook. The style should be cute, whimsical, and colorful, with soft, rounded shapes. The characters should have expressive, happy faces. The medium should look like colored pencils and gentle watercolors.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-food-after.webp',
    },
    {
        id: 'pro_stock_photo_1',
        category: 'Professional',
        title: 'template_pro_stock_photo_1_title',
        description: 'template_pro_stock_photo_1_description',
        prompt: `Analyze the people and setting in the provided photo. Recreate the scene as a bright, clean, and modern stock photo. The people should be smiling and engaged, looking at a laptop screen. The environment should be a bright and airy office. The final image should convey themes of teamwork, success, and diversity. Photorealistic, 4k.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-after.webp',
    },
    {
        id: 'photo_fisheye_1',
        category: 'Photography',
        title: 'template_photo_fisheye_1_title',
        description: 'template_photo_fisheye_1_description',
        prompt: `Apply a fisheye lens effect to the provided photograph. The perspective should be extremely wide and distorted, with curved lines at the edges of the frame. The effect should be dynamic and immersive.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-tilt-shift-after.webp',
    },
    {
        id: 'utility_pattern_1',
        category: 'Utility',
        title: 'template_utility_pattern_1_title',
        description: 'template_utility_pattern_1_description',
        prompt: `Using the style and elements of the provided image, generate a seamless, tileable, geometric pattern in an Art Deco style. The design must be elegant, symmetrical, and perfectly repeatable. The final output should be in a high-resolution vector style.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-after.webp',
    },
    {
        id: 'char_superhero_1',
        category: 'Character Design',
        title: 'template_char_superhero_1_title',
        description: 'template_char_superhero_1_description',
        prompt: `Transform the person in the photo into a new superhero. Her costume should be sleek and aerodynamic, primarily dark purple and silver, with glowing cyan lines that pulse with energy. She should be posed in a dynamic action pose. Redraw in the comic book art style of Jim Lee.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-comic-after.webp',
    },
    {
        id: 'env_underwater_1',
        category: 'Environment & Worlds',
        title: 'template_env_underwater_1_title',
        description: 'template_env_underwater_1_description',
        prompt: `Transform the provided city photo into a majestic, sprawling city built on the ocean floor. The buildings should be made bioluminescent. Add giant domes of reinforced glass protecting lush green parks inside. Add schools of exotic fish and giant whales swimming between the buildings. Light should filter down from the surface far above.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-archviz-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-after.webp',
    },
    {
        id: 'art_charcoal_1',
        category: 'Artistic',
        title: 'template_art_charcoal_1_title',
        description: 'template_art_charcoal_1_description',
        prompt: `Redraw the provided portrait as a realistic, expressive charcoal sketch. The drawing should have a high level of detail, especially in the wrinkles and eyes. The texture of the charcoal on rough paper should be visible. Use a full range of tones, from deep blacks to smudged grays and white highlights.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-restore-after.webp',
    },
    {
        id: 'ui_loading_anim_1',
        category: 'UI & Icons',
        title: 'template_ui_loading_anim_1_title',
        description: 'template_ui_loading_anim_1_description',
        prompt: 'From the central object in the provided image, create a concept for a loading animation (spinner). The design should be a circle made of smaller dots that individually light up and fade in a continuous, flowing loop. The color should be a soothing blue. The animation should look smooth and modern. Render as a clean vector, isolated on a dark background.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-hologram-after.webp',
    },
    {
        id: 'scifi_dyson_sphere_1',
        category: 'Abstract & Sci-Fi',
        title: 'template_scifi_dyson_sphere_1_title',
        description: 'template_scifi_dyson_sphere_1_description',
        prompt: 'Use the provided space image as a backdrop to create a wide-angle shot of a partially completed Dyson sphere megastructure around the central star. The scale should be immense, with continent-sized panels being moved into place. The inner surface of the completed sections should be visible, showing city lights and green landscapes. The style should be epic sci-fi concept art.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-after.webp',
    },
    {
        id: 'fun_board_game_1',
        category: 'Creative & Fun',
        title: 'template_fun_board_game_1_title',
        description: 'template_fun_board_game_1_description',
        prompt: `Redraw the character from the provided image as art for a card in a fantasy board game. The art should depict the character in a style that is colorful, slightly stylized, and family-friendly.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-pixel-after.webp',
    },
    {
        id: 'photo_food_flatlay_1',
        category: 'Photography',
        title: 'template_photo_food_flatlay_1_title',
        description: 'template_photo_food_flatlay_1_description',
        prompt: 'Recreate the provided image of a meal as a top-down flatlay photograph. The composition should be carefully arranged and aesthetically pleasing on a rustic wooden table. The lighting should be bright and natural.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-food-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-food-after.webp',
    },
    {
        id: 'utility_map_1',
        category: 'Utility',
        title: 'template_utility_map_1_title',
        description: 'template_utility_map_1_description',
        prompt: 'Transform the provided landscape image into a fantasy world map in the style of a hand-drawn, Tolkien-esque map. The key features of the landscape should be represented as stylized mountains, forests, and rivers. The paper should look aged and yellowed, with a compass rose in the corner. The style is ink and parchment.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-restore-after.webp',
    },
    {
        id: 'char_ghost_1',
        category: 'Character Design',
        title: 'template_char_ghost_1_title',
        description: 'template_char_ghost_1_description',
        prompt: `Transform the person or object in the photo into a cute and friendly ghost character. It should be small, white, and translucent, with big, curious black eyes. It should be floating happily and waving. The style should be a simple, clean 3D render, suitable for an animated children's movie.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-pixel-after.webp',
    },
    {
        id: 'env_cyberpunk_market_1',
        category: 'Environment & Worlds',
        title: 'template_env_cyberpunk_market_1_title',
        description: 'template_env_cyberpunk_market_1_description',
        prompt: `Transform the provided city photo into a bustling street-level night market in a dense cyberpunk city. The scene should be crowded with people and androids. Add steaming food stalls, illuminated by colorful, glowing neon signs in various languages. The air should be hazy with rain and smog. Add giant holographic advertisements flickering high above. The final image should be moody, atmospheric, and highly detailed.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-comic-after.webp',
    },
    {
        id: 'art_impressionist_1',
        category: 'Artistic',
        title: 'template_art_impressionist_1_title',
        description: 'template_art_impressionist_1_description',
        prompt: `Repaint the provided photo as an impressionist painting, in the style of Claude Monet. The focus should be on the play of light on the scene. The brushstrokes should be short, thick, and visible. The colors should be soft and natural. The overall feeling should be peaceful and serene.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-style-after.webp',
    },
    {
        id: 'ui_button_set_1',
        category: 'UI & Icons',
        title: 'template_ui_button_set_1_title',
        description: 'template_ui_button_set_1_description',
        prompt: `Using the provided image as a background, create a set of UI buttons (Play, Pause, Stop) designed with the glassmorphism aesthetic. The buttons should look like frosted glass, with a semi-transparent background, a subtle border, and a soft shadow to make them appear to float over the background.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-hologram-after.webp',
    },
    {
        id: 'scifi_ship_interior_1',
        category: 'Abstract & Sci-Fi',
        title: 'template_scifi_ship_interior_1_title',
        description: 'template_scifi_ship_interior_1_description',
        prompt: 'Use the provided image as the main viewport view from the bridge of a sleek, modern spaceship. The rest of the image should be the interior of the bridge, which is clean and minimalist, with holographic displays and control panels. The lighting should be cool and blue. Photorealistic and cinematic.',
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-hologram-after.webp',
    },
    {
        id: 'fun_coloring_book_1',
        category: 'Creative & Fun',
        title: 'template_fun_coloring_book_1_title',
        description: 'template_fun_coloring_book_1_description',
        prompt: `Transform the provided image into a coloring book page. The design should be an intricate line drawing based on the original image's subject. The lines should be clean, black, and of a consistent thickness. The image should be entirely black and white, with no shading. High resolution and ready to print.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-logo-after.webp',
    },
    {
        id: 'vxdl_persona_skin_1',
        category: 'VXDL PERSONA',
        title: 'template_vxdl_persona_skin_1_title',
        description: 'template_vxdl_persona_skin_1_description',
        prompt: `CRITICAL REFINEMENT DIRECTIVE: You are an expert digital image refiner, tasked with elevating a portrait to hyper-realism. Analyze the person in the provided photograph. Your primary objective is to meticulously render the skin with ultra-high fidelity. Recreate the skin texture to include subtle pores, micro-imperfections, and the natural sheen of human skin under professional lighting. Enhance the complexity of all textures, including the fabric of their clothing and individual strands of hair. Apply a 'reality camera look' by simulating the properties of a high-end portrait lens: introduce a shallow depth of field to create a soft, blurred background (bokeh), apply a very fine, almost imperceptible film grain, and perform professional color grading to achieve a cinematic, true-to-life color palette. NON-NEGOTIABLE: The subject's facial features, identity, and likeness must be perfectly preserved. You are refining, not replacing.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-after.webp',
    },
    {
        id: 'vxdl_persona_emotion_1',
        category: 'VXDL PERSONA',
        title: 'template_vxdl_persona_emotion_1_title',
        description: 'template_vxdl_persona_emotion_1_description',
        prompt: `CRITICAL REFINEMENT DIRECTIVE: You are an expert in micro-expressions and digital portraiture. Analyze the person in the provided photograph. Your task is to subtly alter their facial expression to convey [TARGET EMOTION, e.g., 'a soft, gentle smile', 'a look of thoughtful contemplation', 'a hint of amusement']. This is a task of extreme subtlety. All changes must be photorealistic and consistent with the subject's facial structure. Do not change their identity. The lighting and overall image quality must be preserved and enhanced to match the new emotion. NON-NEGOTIABLE: The subject's likeness must remain perfectly intact, only the expression should be altered.`,
        beforeImage: 'https://storage.googleapis.com/vxdl-public-assets/template-headshot-before.webp',
        afterImage: 'https://storage.googleapis.com/vxdl-public-assets/template-rpg-after.webp',
    }
];